# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

In [26]:
 #crea un arrelo de ceros de longuitud 12
 arreglo_1 = np.zeros(12)
 arreglo_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#2 crea un arrego de longuitud 10 con ceros en todas sus posiciones y un10 en la posicion 5
import numpy as np

In [ ]:
 arreglo_2 = np.zeros(12)
 arreglo_2[5] = 10
 arreglo_2

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
import numpy as np


In [ ]:
#3
arreglo_3 = np.arange(10,49+1,1)
arreglo_3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
import numpy as np

In [ ]:
 #4
 arreglo_4 = np. arange(0, 9, 1).reshape((3, 3))
 arreglo_4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
import numpy as np

In [ ]:
#5
arreglo_5 =np.random.randint (1000, size=  (100))
print( f"Media: {np.mean(arreglo_5)}")
print(f"Varianza: {np.var(arreglo_5)}")

Media: 508.98
Varianza: 76183.79959999998


In [ ]:
suma = np.sum (arreglo_5)
media = suma/arreglo_5.size
media

508.98

In [ ]:
#6
arreglo_6 = np.random.randn(2, 4)
arreglo_6

array([[ 0.53556518,  0.82814885, -1.24909764,  0.54428888],
       [ 0.26350998, -0.28345713,  0.60077983, -0.29303455]])